config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  root "welcome#home"
  get "about" => "welcome#about"

  resources :articles 

  get "/users/index" => "users#index"
  get "signup" => "users#new"
  post "users" => "users#create" 
  get "/users/:id/edit" => "users#edit"
  get "users/:id/show" => "users#show"
  patch "/users/:id/update" => "users#update"

  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

end

app/models/article.rb
class Article < ActiveRecord::Base
    acts_as_votable
    # has_many :likes
    belongs_to :user
    validates :title, presence: true, length: { minimum: 3, maximum: 50 }
    validates :description, presence: true, length: { minimum: 3, maximum: 300 }
    validates :user_id, presence: true
end

app/models/like.rb
class Like < ActiveRecord::Base
    belongs_to :users
    belongs_to :articles
end

app/models/user.rb
class User < ActiveRecord::Base
    acts_as_voter
    # has_many :likes, dependent: :destroy
    has_many :articles
    # has_many :articles_liked, through: :likes, source: :articles
    has_secure_password
    #before_save { self.email = email.downcase } # changing all emails to lower case
    EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i
    NORM_REGEX = /\A[a-zA-Z0-9\s]+\z/i
    validates :username, presence: true, length: { minimum: 3, maximum: 50 }, uniqueness: { case_sensitive: false}, format: { with: NORM_REGEX, message: "Can Only Contain Letters And Numbers." }
    validates :email, presence: true, length: { minimum: 3, maximum: 100 }, uniqueness: { case_sensitive: false }, format: { with: EMAIL_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user || User.find(session[:user_id]) if session[:user_id] # return this user if their is a session id, if so then find the user in the data base
  end

  def logged_in?
    !!current_user  # converting into a bolean
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :require_user, except: [:index, :show, :vote, :new] # except for the index and show action we need a logged in user
    before_action :require_same_user, only: [:edit, :update, :destroy] # further ensuring only current user can have access to these actions
    respond_to :js, :json, :html

    def index
        if !logged_in?
            flash[:danger] = "You must be logged in to access articles!"
            redirect_to root_path
        else
            @articles = Article.paginate(page: params[:page], per_page: 5)  #instead of Article.all, we have added evertything to show in pages
        end
    end

    def new
        @article = Article.new
    end

    def edit
        # require_same_user
        @article = Article.find(params[:id]) # pulls the already exisiting info
    end

    def create
        @article = Article.new(article_params) #white listing
        @article.user = current_user
        if @article.save
            flash[:notice] = "Article was successfully created"
            redirect_to article_path(@article)
        else
            render "new" 
        end
    end

    def update
        @article = Article.find(params[:id])
        if @article.update(article_params) #white listing
            flash[:notice] = "Article was updated!"
            redirect_to article_path(@article)
        else
            render "edit"
        end
    end

    def show
        @article = Article.find(params[:id]) #Show article id from the params hash
    end

    def destroy
        @article = Article.find(params[:id])
        @article.destroy
        flash[:notice] = "Article was successfully deleted!"
        redirect_to articles_path
    end

    # def liked
    #     if params[:articles] == "like"
    #       User.find(current_user.id).likes.create(article:Article.find(params[:articles_id]))
    #     end
    #     if params[:articles] == "unlike"
    #       User.find(current_user.id).likes.find(params[:articles_id]).destroy
    #     end
    #     redirect_to articles_path
    # end

    def vote
        @article = Article.find(params[:id]) #Show article id from the params hash
        if !current_user.liked? @article
            @article.liked_by current_user
        elsif current_user.liked? @article
            @article.unliked_by current_user
        end
    end

    private
    def article_params
        params.require(:article).permit(:title, :description) # Making them private yet allowing title and description to be allowed through the params hash
    end

    def require_same_user
        @article = Article.find(params[:id]) # Since this is a before action, you must reclarify youre instance variables
        if current_user != @article.user
            flash[:danger] = "You can only manipulate your own articles"
            redirect_to root_path
        end
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new

    end

    def create 
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:success] = "You have successfully logged in!"
            redirect_to "/users/#{user[:id]}/show"
        else
            flash.now[:danger] = "Your username and/or password was incorrect!"
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:success] = "You have logged out!"
        redirect_to root_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_same_user, only: [:edit, :update]

  def index
    if !logged_in?
      flash[:danger] = "You must be logged in to access users!"
      redirect_to root_path
    else
      @users = User.paginate(page: params[:page], per_page: 5)
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome To The Alpah Blog #{@user.username}"
      redirect_to "/users/#{@user[:id]}/show"
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id]) # pulls the already exisiting info
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params) #white listing
        flash[:success] = "User was updated!"
        redirect_to articles_path
    else
        render "edit"
    end
  end

  def show
    @user = User.find(params[:id])
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def require_same_user
    @user = User.find(params[:id]) # Since this is a before action, you must reclarify youre instance variables
    if current_user != @user
      flash[:danger] = "You can only edit your own account"
      redirect_to root_path
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def home
        redirect_to articles_path if logged_in? # if logged in then redirect to articles page
    end

    def about

    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def gravatar_for(user, options = {size: 80 })
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.username, class: "img-circle")
    end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_article.html.erb
<%# changed the @article to be usable in a partials to obj %>
<% obj.each do |article| %>
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
            <div class="well well-lg">
                <div class="article-title">
                    <%= link_to article.title, article_path(article) %>
                </div>
                <div class="article-body">
                   <%= article.description %>
                   <br>
                   <div class="article-meta-details">
                        <small>Created by: <%= article.user.username if article.user %>,
                    </div>
                    <%# Puts  in a nice formatting %>
                    <div class="time">
                        <%= time_ago_in_words(article.created_at) %> ago
                        <br> 
                        last updated: <%= time_ago_in_words(article.updated_at) %> ago </small>
                    </div>

                    <%# Likes button Currently broken trying to utilize upvote%>
                    

                    <%# Likes button %>

                </div>
                <%# Restrict actions unless current user is valid %>
                <% if logged_in? && current_user == article.user %>
                <div class"article-actions">
                    <%= link_to "Edit", edit_article_path(article), class: "btn btn-xs btn-success" %>
                    <%= link_to "Show", article_path(article), class: "btn btn-xs btn-primary" %>
                    <%# Destroy method with confirmations %>
                    <%= link_to "Delete", article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>
                </div>
                <% end %>
            </div>
        </div>
    </div>
<% end %>
</table>
<br>

app/views/articles/_form.html.erb
<!DOCTYPE html>

<%# Flash errors if %>
<% if @article.errors.any? %>
<h3>The Following Errors Provented Your submission</h3>
<ul>
    <% @article.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
</ul> 
<% end %>
<%# Submittion of create/add %>

<%# Form css addition %>
<div class='row'>
    <div class ='col-xs-12'>
        <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |i| %>
        <div class ="form-group">
            <div class ="control-label col-sm-2"
            <%= i.label :title %>
        </div>
        <div class ="col-sm-5">
            <%= i.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %> 
        </div>
      </div>
      <div class ="form-group">
            <div class ="control-label col-sm-2"
            <%= i.label :description %>
            <br>
            </div>
            <br>
                <div class ="col-sm-7">
                    <%= i.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                <br>
                <%= i.submit class: "btn btn-primary btn-lg" %>
                </div>
            </div>
        <% end %>
    
        <p align="center">[<%= link_to "Go Back To Articles", articles_path %>]
    </div>
</div>
</html>

app/views/articles/edit.html.erb
<!DOCTYPE html>
<h1 align="center"> Edit The Article:</h1>

<%# Utilizing partials to cutt down on redundancy, refer to    _forms.html.erb %>
<%# *NOTE* if in diff directory, put in path, example: "otherFolder/forms" %>
<%= render 'form' %>
</html>

app/views/articles/index.html.erb
<!DOCTYPE html>
<h1 align="center">Listing All Articles</h1>
<p align="center"><%= link_to "Create New article", new_article_path, class: "btn btn-xs btn-success" %> 
<table class = "border">

<div align="center">
    <%= will_paginate %>
</div>

<%# what were doing below is saying that when the obj is called user @articles as value for obj %>
<%= render 'article', obj: @articles %>
<div align="center">
    <%= will_paginate %>
</div>

</html>

app/views/articles/new.html.erb
<!DOCTYPE html>
<h1 align="center"> Create An Article:</h1>

<%# Utilizing partials to cutt down on redundancy, refer to    _forms.html.erb %>
<%# *NOTE* if in diff directory, put in path, example: "otherFolder/forms" %>
<%= render 'form' %>
</html>

app/views/articles/show.html.erb
<!DOCTYPE html>
<h1 align="center">Showing: <%= @article.title %></h1>
<div class="well col-xs-8 col-xs-offset-2">
<%# Info about creator %>
<ul class="listing">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <li>Created By: </li>
                <li><%= link_to gravatar_for(@article.user), "/users/#{@article.user[:id]}/show" %></li>
                <li class="article-title">
                    <%= link_to @article.user.username, "/users/#{@article.user[:id]}/show" %>
                </li>
                <li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></li>
            </div>
        </div>
    </ul> 
<%# Info about creator %>

    <h4 class="center"><strong>Description:</strong></h4>
    <hr>
    <%= @article.description %>

<p>Description: <%= @article.description %></p>

    <%= link_to "Delete", article_path(@article), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %> |
    <%= link_to 'Home', root_path, class: "btn btn-xs btn-primary" %> |
    <%= link_to 'Edit', edit_article_path, class: "btn btn-xs btn-success" %>
</div>
</html>

app/views/articles/vote.js.erb
<% if current_user.liked? @articles %>
    $('.like-btn').addClass('liked);
<% else %>
    $('.like-btn').removeClass('liked');
<% end %>
    $('.likes-count').html("<%= @articles.get_upvotes.size %>")

app/views/layouts/_footer.html.erb
<div class="contrainer">
    <footer class="footer">
        <small>
        <p align="center"> Copyright &copy; <a href="https://www.ruby-lang.org/en/">The Complete Road To RUBY!</a>
        by <a href="#"> Ryan Smith </a>
        </small>
        <nav class="fnav">
            <ul>
                <li><p align="center"><%= link_to "About Ryan", about_path %></li>
            </ul>
        </nav>
    </footer>
</div>

app/views/layouts/_navigation.html.erb
<%# Bootstrap.com navbar %>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%# <a class="navbar-brand" id = "logo" href="#">Alpha Blog</a> %>
      <%= link_to "Alpha Blog", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      <% if logged_in? %>
        <%# <li><a href="#">Link <span class="sr-only">(current)</span></a></li> %>
        <li><%= link_to "Articles", articles_path, id: "navcolor" %></li>
        <li><a href="/users/index", id="navcolor">Show Users</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle", id="navcolor", data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "New Article", new_article_path, id: "navcolor" %></li>
              <li><a href= "/users/<%= current_user.id %>/show" id ="navcolor" >View Your Profile</a></li>
              <li><%= link_to "Show All Articles", articles_path, id: "navcolor" %></li>
              <li><a href="/users/index", id="navcolor">Show All Users</a></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log Out", logout_path, method: :delete, id: "navcolor" %></li>
            </ul>
          </li>
        <% end %>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
      <% if logged_in? %>
      <li><a href= "/users/<%= current_user.id %>/show" id ="navcolor" >View Your Profile</a></li>
      <li><%= link_to "Log Out", logout_path, method: :delete, id: "navcolor" %></li>
        
    <% else %>
      <li><%= link_to "Login", login_path, id: "navcolor" %></li>
      <li><%= link_to "Signup", signup_path, id: "navcolor" %></li>
    <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%# Nav bar %>
<%= render "layouts/navigation" %>
<div class="container">
<%# will flash across all pages! %>
  <% flash.each do |name, msg| %>
    <ul>
      <li><%= msg %></li>
    </ul>
  <% end %>

<%# will flash across all pages! %>
<%= yield %>
</div>
<%= render "layouts/footer" %>


</body>
</html>

app/views/users/edit.html.erb
<!DOCTYPE html>
<h1 align="center"> Edit Your Account</h1>

<%# Flash errors if %>
<% if @user.errors.any? %>
<h3>The Following Errors Provented Your submission</h3>
<ul>
    <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
</ul> 
<% end %>
<%# Submittion of create/add %>

<%# Form css addition %>
<div class='row'>
    <div class ='col-xs-12'>
    <%# had to add action under the for_forms becuase of issue with paths? %>
        <%= form_for(@user, url: {action: "update"}, :html => {class: "form-horizontal", role: "form"}) do |i| %>
        <div class ="form-group">
            <div class ="control-label col-sm-2"
            <%= i.label :username %>
        </div>
        <div class ="col-sm-5">
            <%= i.text_field :username, class: "form-control", placeholder: "Enter Username Here", autofocus: true %> 
        </div>
      </div>
      <div class ="form-group">
            <div class ="control-label col-sm-2"
            <%= i.label :email %>
            <br>
            </div>
            <br>
                <div class ="col-sm-7">
                    <%= i.email_field :email, class: "form-control", placeholder: "Enter Email Here" %>
                </div>
            </div>
            <%# -------Password------ %>
            <div class ="form-group">
            <div class ="control-label col-sm-2"
            <%= i.label :password %>
            <br>
            </div>
            <br>
                <div class ="col-sm-7">
                    <%= i.password_field :password, class: "form-control", placeholder: "Enter Password Here" %>
                </div>
            </div>
            <%# -------Password------ %>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                <br>
                <%= i.submit "Update Your Account", class: "btn btn-primary btn-lg" %>
                </div>
            </div>
        <% end %>
    
        <p align="center">[<%= link_to "Go Back To Articles", articles_path %>]
    </div>
</div>
</html>

app/views/users/index.html.erb
<h1 align ="center"> All Alpha Bloggers</h1>
<div align="center">
    <%= will_paginate %>
</div>
<% @users.each do |user| %>
    <ul class="listing">
        <div class="row">
            <div class="well col-md-4 col-md-offset-4">
                <li><%= link_to gravatar_for(user), "/users/#{user[:id]}/show" %></li>
                <li class="article-title">
                    <%= link_to user.username, "/users/#{user[:id]}/show" %>
                </li>
                <li><small><%= pluralize(user.articles.count, "article") if user.articles %></small></li>
            </div>
        </div>
    </ul> 
<% end %>
<div align="center">
    <%= will_paginate %>
</div>

app/views/users/new.html.erb
<!DOCTYPE html>
<h1 align="center"> Signup For Alpha Blog </h1>
<%# Flash errors if %>
<% if @user.errors.any? %>
<h4>The Following Errors Provented Your submission</h4>
<ul>
    <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
</ul> 
<% end %>

<%# Submittion of create/add %>

<%# Form css addition %>
<div class='row'>
    <div class ='col-xs-12'>
        <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |i| %>
        <div class ="form-group">
            <div class ="control-label col-sm-2">
            <%= i.label :username %>
        </div>
        <div class ="col-sm-7">
            <%= i.text_field :username, class: "form-control", placeholder: "Enter Username Here", autofocus: true %> 
        </div>
      </div>
      <div class ="form-group">
            <div class ="control-label col-sm-2">
            <%= i.label :email %>
            </div>
                <div class ="col-sm-7">
                    <%= i.email_field :email, class: "form-control", placeholder: "Enter Email Here" %>
                </div>
            </div>
            <%# -------Password------ %>
            <div class ="form-group">
            <div class ="control-label col-sm-2">
            <%= i.label :password %>
            </div>
                <div class ="col-sm-7">
                    <%= i.password_field :password, class: "form-control", placeholder: "Enter Password Here" %>
                </div>
            </div>
            <%# -------Password------ %>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                <br>
                <%= i.submit "Sign Up", class: "btn btn-primary btn-lg" %>
                </div>
            </div>
        <% end %>
    
        <p align="center"><%= link_to "Go Back To Home", root_path, class: "btn btn-xs btn-success" %>
        
    </div>
</div>
</html>

app/views/users/show.html.erb
<h1 align="center"> Welcome To <%= @user.username %>'s page</h1>
<div class="row">
    <div class="col-md-4 col-md-offset-4 center">
    <%= gravatar_for @user, size: 150  %>
    </div>
</div>
<h4 align="center"><%= @user.username %>'s Articles</h4>
<div class="center">
    <%= will_paginate @user_articles %>
</div>
<p align="center"><%= link_to 'Go To Users List', users_index_path, class: "btn btn-xs btn-success" %> | <%= link_to 'Go To Articles List', articles_path, class: "btn btn-xs btn-primary" %></p>
<%# changing render 'articles/article', obj: @user.articles to below: %>
<%= render 'articles/article', obj: @user_articles %> 
<div class="center">
    <%= will_paginate @user_articles %>
</div>

app/views/welcome/about.html.erb
<!DOCTYPE html>
<h1> This is the about page!</h1>
<style>
.about{
    color: red;
    font-weight: bold
}
</style>
<h3 class = "about">IF YOU AINT KNOWIN ABOUT RYAN THEN..... GO FUCK YOURSELF! YOU OBVIOUSLY AINT ABOUT THAT LIFE SON!</h3>
<h4 class = "about">You think water moves fast? You should see ice. It moves like it has a mind. Like it knows it killed the world once and got a taste for murder. After the avalanche, it took us a week to climb out. Now, I don't know exactly when we turned on each other, but I know that seven of us survived the slide... and only five made it out. Now we took an oath, that I'm breaking now. We said we'd say it was the snow that killed the other two, but it wasn't. Nature is lethal but it doesn't hold a candle to man.</h4>
<p align="center"><%= link_to 'Home', root_path, class: "btn btn-success btn-lg" %></p>
</html>

app/views/welcome/home.html.erb
<!DOCTYPE html>
<div class="center jumbotron">
    <h1 id="alphaText">ALPHA BLOG</h1>
    <br>
    <br>
    <%= link_to "Sign Up Now", signup_path, class: "Btn btn-danger btn-lg btn-xlarge" %>
    <br>
    <br>
    <br>
    <%= link_to "Login", login_path, class: "Btn btn-success btn-lg btn-xlarge2" %>
    
</div>
</html>